### ISSUE TITLE
Redmine 4.0, page index error 500

### ISSUE THREAD

**Issue by vsc55** [syntacticvexation/redmine_favourite_projects#65]
Hi,

In the index page show error Internal Server.

Show in the log:
```
Completed 500 Internal Server Error in 21ms (ActiveRecord: 12.5ms)
  
NoMethodError (undefined method `member?' for #<ActionController::Parameters:0x0000555ca4b22c20>):
  
plugins/redmine_favourite_projects/app/controllers/favourite_projects_controller.rb:8:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Best regards.

**Comment by vsc55** [comment]
ok, checked and function correctly. 👍
